# 影子交易测试配置（10 分钟快速验证）
# 用于验证系统是否正常工作

# 继承基础配置
base_config: "base.yaml"

# 运行环境
environment: "mainnet"

# 影子交易模式
shadow_mode:
  enabled: true
  duration_hours: 1.0  # 1 小时完整测试
  start_time: null  # 立即开始

  # 成交模拟配置
  fill_simulation:
    method: "realistic"
    max_slippage_bps: 50.0
    partial_fill_enabled: true

  # 初始资金
  initial_nav: 100000

  # Week 2 混合订单配置
  orders:
    # IOC 订单配置（高置信度）
    ioc:
      enabled: true
      default_size: 0.01
      price_adjustment_bps: 10.0  # IOC 加价以确保成交

    # 限价单配置（中等置信度）
    limit:
      enabled: true
      default_size: 0.01
      timeout_seconds: 5.0  # 超时后撤单
      use_post_only: true  # 确保成为 Maker

    # 订单路由配置
    routing:
      enable_fallback: true  # 限价单超时后回退到 IOC
      fallback_timeout_seconds: 5.0

# 信号配置
signals:
  aggregation:
    method: "weighted_average"
    min_confidence: 0.1

  thresholds:
    theta_1: 0.7  # 高置信度（提高到 0.7 减少过度交易）
    theta_2: 0.4  # 中置信度（提高到 0.4 过滤低质量信号）

  # 信号源
  sources:
    obi:
      enabled: true
      weight: 0.4
      levels: 5
    microprice:
      enabled: true
      weight: 0.3
    impact:
      enabled: true
      weight: 0.3

# 分析配置（测试用更短的窗口）
analytics:
  ic_calculation:
    window_hours: 0.5  # 30 分钟 IC 窗口
    min_samples: 30  # 标准最小样本数
    update_interval_minutes: 2  # 更频繁的更新

  # 未来收益跟踪（用于 IC 计算）
  future_return:
    window_minutes: 10  # T+10 分钟收益窗口
    update_interval_seconds: 10  # 每 10 秒更新一次

  pnl_attribution:
    update_interval_minutes: 2
    save_to_file: true
    output_dir: "logs/shadow_test"

  # 上线标准（测试用，标准相同）
  launch_criteria:
    ic_min: 0.03
    alpha_pct_min: 70.0
    cost_pct_max: 25.0
    uptime_pct_min: 99.0  # 测试时降低一点
    p99_latency_ms_max: 150.0
    win_rate_min: 60.0

# 实时监控（测试用更频繁）
monitoring:
  live_monitor:
    enabled: true
    update_interval_seconds: 30  # 每 30 秒更新

    alert_thresholds:
      latency_ms: 200
      fill_rate_pct: 80
      drawdown_pct: 3.0
      consecutive_losses: 5

  logging:
    level: "INFO"
    format: "json"
    file_rotation: "daily"
    output_dir: "logs/shadow_test"

    include_fields:
      - "timestamp"
      - "event"
      - "symbol"
      - "signal_value"
      - "confidence"
      - "execution_result"
      - "latency_ms"
      - "pnl"

# 数据配置
data:
  orderbook:
    levels: 10
    update_frequency: 100

  persistence:
    enabled: true
    save_interval_minutes: 5  # 测试时更频繁保存
    output_dir: "data/shadow_test"
    formats:
      - "parquet"
      - "json"

# Hyperliquid 连接
hyperliquid:
  endpoint: "mainnet"

  websocket:
    reconnect_enabled: true
    reconnect_max_attempts: 10
    reconnect_delay_seconds: 5
    heartbeat_interval_seconds: 30

  subscriptions:
    symbols:
      - "BTC"
      - "ETH"
    channels:
      - "l2Book"
      - "trades"
      - "user"

# 风控配置
risk:
  hard_limits:
    max_single_loss_pct: 0.008
    max_daily_drawdown_pct: 0.05
    max_position_size_usd: 10000

  position:
    max_leverage: 5
    inventory_target: 0
    inventory_tolerance: 0.2

# 报告配置
reporting:
  realtime:
    enabled: true
    interval_minutes: 5  # 测试时更频繁
    include_charts: true

  final_report:
    enabled: true
    output_dir: "docs/shadow_test"
    formats:
      - "html"
      - "json"
      - "markdown"

    sections:
      - "summary"
      - "signal_quality"
      - "execution_efficiency"
      - "risk_metrics"
      - "pnl_attribution"
      - "launch_readiness"
